class UsersController < ApplicationController
	# User methods and back-end is, for the most part, auto-generated by the devise gem. This defines the show method for users.
	def show
		@user = User.includes(:vote_options).find_by_id(params[:id])
	end
end